### PR TITLE
chore(deps): upgrade to node v16.16.0

### PR DESCRIPTION
**Pull request by gidjin**
# SC-244

## Proposed changes

Upgrade to node version 16.16.0

---

## Reviewer notes

Recommend deleting `node_modules` before continuing. But not required.

## Setup

Make sure the client runs successfully

```sh
yarn portal:up
yarn dev
```

---

### As the original developer, I have

- [X] Met the acceptance criteria, or will meet them in subsequent PRs or stories

### As code reviewer(s), I have

- [ ] Pulled this branch locally and tested it
- [ ] Reviewed this code and left comments
- [ ] Checked that all code is adequately covered by tests
- [ ] Made it clear which comments need to be addressed before this work is merged
- [ ] Considered marking this as accepted even if there are small changes needed
- Performed [a11y testing](https://github.com/trussworks/accessibility/blob/master/sample_a11y_testing_process.md):
  - [ ] Checked responsiveness in mobile, tablet, and desktop
  - [ ] Checked keyboard navigability
  - [ ] Tested with [VoiceOver](https://dequeuniversity.com/screenreaders/voiceover-keyboard-shortcuts) in Safari
  - [ ] Checked VO's [rotor menu](https://github.com/trussworks/accessibility/blob/master/README.md#how-to-use-the-rotor-menu) for landmarks, page heading structure and links
  - [ ] Used a browser a11y tool to check for issues (WAVE, axe, ANDI or Accessibility addon tab for Storybook)

### As a designer reviewer, I have

- [ ] Checked in the design translated visually
- [ ] Checked behavior
- [ ] Checked different states (empty, one, some, error)
- [ ] Checked for landmarks, page heading structure, and links
- [ ] Tried to break the intended flow
- Performed [a11y testing](https://github.com/trussworks/accessibility/blob/master/sample_a11y_testing_process.md):
  - [ ] Checked responsiveness in mobile, tablet, and desktop
  - [ ] Checked keyboard navigability
  - [ ] Tested with [VoiceOver](https://dequeuniversity.com/screenreaders/voiceover-keyboard-shortcuts) in Safari
  - [ ] Checked VO's [rotor menu](https://github.com/trussworks/accessibility/blob/master/README.md#how-to-use-the-rotor-menu) for landmarks, page heading structure and links
  - [ ] Used a browser a11y tool to check for issues (WAVE, axe, ANDI or Accessibility addon tab for Storybook)

---

### CODE REVIEW

**Review by esacteksab — APPROVED** [review]
If the tests pass, :shipit:

**Review by jcbcapps — APPROVED** [review]
LGTM but wanted to note a couple of things:

1. The setup instructions didn't work for me. I had to run `yarn services:up && yarn dev` and then run `yarn dev` in the client repo. The portal did run as expected, and this is probably something to do with my local machine, but just thought it might be worth mentioning in case anyone else had the issue.
2. When running the e2e tests, I see the `type "UserRoleType" does not exist` error that you mentioned a few days back. I tried to figure out what it might be, but was unsuccessful. I swapped to `main` and saw that the e2e tests were failing with the same error, so I'm not sure what is going on there, but that confirms to me that it has nothing to do with this PR. Strange that those same tests are passing in GitHub Actions, so must be something on my local machine. Just thought it worth mentioning.

**Review by abbyoung — APPROVED** [review]

**Comment by abbyoung** [comment]
e2e tests passing for me with no errors; no lint errors ✅

**Comment by gidjin** [comment]
We did some investigation and locally e2e tests seem fairly unstable as they will regularly fail but sometimes pass. Not entirely sure this is due to the node 16 upgrade but it was too consistent locally to allow us to move forward. We met and we've decided we're not comfortable pushing this through. node 14 is LTS until April next year so we are opting to focus on the e2e test work before tackling the node upgrade.

**Pull request closed without merging**
