### PR TITLE
dev: Update Docker Compose files for local dev

### PR DESCRIPTION
**Pull request by abbyoung**
## Description 

* Adds yarn scripts to control bringing docker containers up/down for services

Fixes #sc-277

## Review Notes

To test Keystone local development: 

* Add `PORTAL_PATH` to `.envrc.local` - holds path to ussf-portal-client directory on your local machine
* Run `yarn services:up` - starts all services required (includes Postgres)
* Or run `yarn portal:up` - starts all services required _and_ Portal
* ...then run `yarn dev` to start Keystone

### CODE REVIEW

**Review by esacteksab — APPROVED** [review]
Interesting solution.

**Review by suzubara — APPROVED** [review]
works as expected!

It might be worth adding this to the `.envrc` file, I had to set it in order to run `yarn dev` while `yarn portal:up` was also running
```
export PORT=3001
```

**Comment by esacteksab** [comment]
> works as expected!
> 
> It might be worth adding this to the `.envrc` file, I had to set it in order to run `yarn dev` while `yarn portal:up` was also running
> 
> ```
> export PORT=3001
> ```

But if `yarn portal:up` wasn't running and you ran `yarn dev` then your node app would be on `3001`, not the default `3000` that you may be used to, right?

**Comment by suzubara** [comment]
> > works as expected!
> > It might be worth adding this to the `.envrc` file, I had to set it in order to run `yarn dev` while `yarn portal:up` was also running
> > ```
> > export PORT=3001
> > ```
> 
> But if `yarn portal:up` wasn't running and you ran `yarn dev` then your node app would be on `3001`, not the default `3000` that you may be used to, right?

Yeah but I think it might be useful to just have the CMS default to a different port so they don't get confused 🤷‍♀️

**Comment by esacteksab** [comment]
> Yeah but I think it might be useful to just have the CMS default to a different port so they don't get confused 🤷‍♀️

Absolutely! Ah, I get it now. New repo (cms instead of client). My bad. The lines are blurring here with everything. Sorry!!

**Pull request merged**
